PACKAGE_NAME="paccel"
PACKAGE_VERSION="@PKGVER@"
MAKE[0]="make KVER=$kernelver DRIVER_CFLAGS=@DRIVER_CFLAGS@"
BUILT_MODULE_NAME[0]="paccel"
DEST_MODULE_LOCATION[0]="/kernel/drivers/usb"
AUTOINSTALL="yes"
